name: Deploy to Vercel on Merge

on:
  push:
    branches:
      - main # Change to 'main' if your branch is named 'main'

permissions:
  contents: read
  deployments: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies and build
        run: |
          npm ci
          npm run build

      - name: Deploy to Vercel using CLI
        run: |
          npm i -g vercel
          vercel --token=$VERCEL_TOKEN --scope=$VERCEL_ORG_ID --yes --prod
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
