name: Deploy to Vercel on PR

on:
  pull_request

permissions:
  contents: read
  deployments: write

jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies and build
        run: |
          npm ci
          npm run build
          npm run lint

      - name: Deploy to Vercel using CLI
        run: |
          npm i -g vercel
          vercel --token=$VERCEL_TOKEN --scope=$VERCEL_ORG_ID --yes --prod
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
