name: Deploy to Vercel on PR

on:
  pull_request

permissions:
  contents: read
  deployments: write

jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies and build
        run: |
          npm ci
          npm run build
          npm run lint
          npm run test

        # Debug step to print Org and Project IDs (Optional)
      - name: Check Vercel Org and Project IDs
        run: |
          echo "Vercel Org ID: $VERCEL_ORG_ID"
          echo "Vercel Project ID: $VERCEL_PROJECT_ID"

      - name: Deploy to Vercel using CLI
        run: |
          npm i -g vercel
          vercel --token=$VERCEL_TOKEN --scope=$VERCEL_ORG_ID --yes --prod
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
